struct signal
{
  int id;
  int value;
  int type;
};

enum signals
{
  POWER_ON,POWER_OFF,MONITOR_ON,MONITOR_OFF,VOICE_ON,VOICE_OFF,MIC_ON,MIC_OFF,SOCK_ON,SOCK_OFF,ROTATE_ON,ROTATE_OFF,
  WATER_ON,WATER_OFF,SMELL_ON,SMELL_OFF,MOVING_ON,MOVING_OFF
};
